CREATE DATABASE IF NOT EXISTS `exam-mcq`;
CREATE DATABASE IF NOT EXISTS `lime-data`;
CREATE DATABASE IF NOT EXISTS `upload_section`;
CREATE DATABASE IF NOT EXISTS `class`;
CREATE DATABASE IF NOT EXISTS `cognitive-style-explanations`;
CREATE DATABASE IF NOT EXISTS `cognitive_load_db`;
